version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - my-app-1.0-SNAPSHOT.jar
    - appsec.yml
  
